version: '3'
services:
    postgres:
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: image_maesto
        ports:
            - 5432:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
    postgres-data:
networks:
    backend:
        driver: bridge
